version: '3.8'

name: northwind-quality

services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: northwind-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - quality-network
      - data-platform-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    user: root

  grafana:
    image: grafana/grafana:10.4.5
    container_name: northwind-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - quality-network
      - data-platform-network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  quality-network:
    external: true
    name: quality-network
  data-platform-network:
    external: true
    name: data-platform-network
