name: northwind-kafka-connect

services:
  kafka-connect:
    image: debezium/connect:2.6.1.Final
    container_name: northwind-connect
    environment:
      BOOTSTRAP_SERVERS: northwind-kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      # Увеличиваем таймауты
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      # REST настройки
      REST_ADVERTISED_HOST_NAME: localhost
      REST_ADVERTISED_PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - connect-network
      - data-platform-network
    restart: unless-stopped
  
  debezium-ui:
    image: quay.io/debezium/debezium-ui:latest
    # image: quay.io/debezium/debezium-ui:2.6.1.Final
    container_name: northwind-debezium-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CONNECT_URIS: http://northwind-connect:8083
    networks:
      - data-platform-network
    depends_on:
      - kafka-connect
    restart: unless-stopped

networks:
  connect-network:
    external: true
  data-platform-network:
    external: true
    