name: northwind-kafka-connect

services:
  kafka-connect:
    image: debezium/connect:2.6.1.Final
    container_name: northwind-connect
    environment:
      BOOTSTRAP_SERVERS: northwind-kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    ports:
      - "8083:8083"
    networks:
      - northwind-net
    restart: unless-stopped

networks:
  northwind-net:
    external: true
    name: northwind-net
    